import Link from "next/link";
import type { ReactNode } from "react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f8f3e9] text-[#3f433f]">
      <Header />

      <main className="mx-auto max-w-4xl px-6 py-12 sm:px-10 sm:py-16">
        {/* INTRO */}
        <div className="max-w-3xl">
          <h1 className="font-serif text-4xl tracking-tight text-[#292d29] sm:text-5xl">
            Terms of Use
          </h1>

          <p className="mt-4 text-sm text-[#888d87]">
            Last updated: 4 September 2026
          </p>

          <div className="mt-8 space-y-4 text-[16px] leading-7 text-[#606660] sm:text-[17px] sm:leading-8">
            <p className="text-lg leading-8 text-[#555b55]">
              These Terms of Use (“Terms”) govern your use of the RealWithin
              mobile application and related services (“RealWithin”, the
              “Service”).
            </p>

            <p>
              By creating an account or using RealWithin, you agree to these
              Terms. If you do not agree to these Terms, please do not use
              RealWithin.
            </p>

            <p>
              RealWithin is operated by V. Bance, an individual developer
              trading as RealWithin.
            </p>
          </div>
        </div>

        {/* TERMS */}
        <div className="mt-12 space-y-10 text-[16px] leading-7 text-[#606660] sm:text-[17px] sm:leading-8">
          <Section title="1. About RealWithin">
            <p>
              RealWithin is a personal reflection application designed to help
              you reflect on your experiences and recognise patterns and
              changes in what you have shared over time.
            </p>

            <p>RealWithin may provide features including:</p>

            <List
              items={[
                "Reflect;",
                "Patterns;",
                "Memory;",
                "You;",
                "AI-generated reflective content;",
                "generated artwork;",
                "notifications; and",
                "other related features introduced over time.",
              ]}
            />

            <p>
              RealWithin is designed for personal reflection and
              self-understanding.
            </p>
          </Section>

          <Section title="2. RealWithin Is Not Therapy or Medical Care">
            <p>
              RealWithin is not a medical, psychological, psychiatric,
              counselling or therapy service.
            </p>

            <p>
              RealWithin does not diagnose medical or mental-health conditions
              and should not be used as a substitute for professional medical,
              psychological, psychiatric or emergency care.
            </p>

            <p>
              Information and reflections generated by RealWithin are provided
              for personal reflection only.
            </p>

            <p>
              If you require medical, psychological or emergency assistance,
              you should seek appropriate professional services.
            </p>
          </Section>

          <Section title="3. AI-Generated Content">
            <p>Some RealWithin features use artificial intelligence.</p>

            <p>
              AI-generated reflections, Patterns, Memories, You recognitions,
              artwork or other outputs may occasionally be inaccurate,
              incomplete or inappropriate.
            </p>

            <p>
              They should not be treated as statements of fact about you.
            </p>

            <p>
              RealWithin is intended to help you notice possibilities in what
              you have shared rather than determine who you are, diagnose you
              or make important decisions for you.
            </p>

            <p>
              You remain responsible for how you interpret or use information
              generated through RealWithin.
            </p>
          </Section>

          <Section title="4. Your Account">
            <p>You may need to create an account to use RealWithin.</p>

            <p>
              You agree to provide accurate account information and to take
              reasonable steps to keep your login details secure.
            </p>

            <p>
              You are responsible for activity through your account where that
              activity results from your failure to protect your login details.
            </p>

            <p>
              If you believe your account has been accessed without permission,
              contact <EmailLink />.
            </p>
          </Section>

          <Section title="5. Your Content">
            <p>
              You retain ownership of the reflections and other original
              content you provide to RealWithin.
            </p>

            <p>
              You give RealWithin permission to process that content only as
              reasonably necessary to operate, maintain and provide the
              Service, including generating RealWithin features for you.
            </p>

            <p>
              This may include processing your content using service providers
              that support RealWithin&apos;s infrastructure and
              artificial-intelligence functionality.
            </p>

            <p>
              Where information you choose to provide contains special-category
              personal information, RealWithin relies on the separate explicit
              consent requested during account creation where required. Your
              agreement to these Terms is separate from that consent.
            </p>

            <p>
              How personal information is handled is explained further in the{" "}
              <Link
                href="/privacy"
                className="font-medium text-[#617166] underline underline-offset-4"
              >
                RealWithin Privacy Policy
              </Link>
              .
            </p>
          </Section>

          <Section title="6. Access to RealWithin">
            <p>
              RealWithin does not currently offer an ongoing free account tier.
            </p>

            <p>
              Eligible new users may access RealWithin through a 14-day Premium
              trial. After the trial ends, an active Premium subscription is
              required to create new Reflections and generate new RealWithin
              understanding.
            </p>

            <p>
              If your trial or paid Premium access ends, you may continue to
              sign in and view RealWithin content that was generated for you
              before access ended.
            </p>

            <p>
              Existing content may remain available on a read-only basis, while
              new Reflections and new Premium-generated understanding remain
              locked until Premium access is restored.
            </p>
          </Section>

          <Section title="7. Premium">
            <p>
              Continued use of RealWithin&apos;s reflection and understanding
              features after an eligible trial requires an active Premium
              subscription.
            </p>

            <p>Premium provides access to features including:</p>

            <List
              items={[
                "Reflect;",
                "Patterns;",
                "Memory;",
                "You; and",
                "other Premium functionality identified within the application.",
              ]}
            />

            <p>Current Premium subscription options include:</p>

            <div className="rounded-[22px] border border-[#e4ded3] bg-[#fffdf8] p-6">
              <p className="font-semibold text-[#414641]">
                Monthly Premium: €11.99 per month
              </p>

              <p className="mt-2 font-semibold text-[#414641]">
                Annual Premium: €114.99 per year
              </p>
            </div>

            <p>
              Actual prices displayed to you may vary according to your country,
              currency, taxes and the pricing shown by the Apple App Store or
              Google Play.
            </p>

            <p>
              The price displayed by the applicable marketplace before purchase
              is the price that applies to that transaction.
            </p>
          </Section>

          <Section title="8. Free Trial">
            <p>
              Eligible new users may receive a 14-day Premium trial.
            </p>

            <p>
              The RealWithin Premium trial does not require payment details and
              does not automatically become a paid subscription when the trial
              ends.
            </p>

            <p>
              To continue creating new Reflections and generating new
              RealWithin understanding after the trial, you must separately
              choose to purchase a Premium subscription through the Apple App
              Store or Google Play.
            </p>

            <p>
              Trial eligibility may be limited and may not be available
              repeatedly to the same user.
            </p>

            <p>
              When the trial ends without an active Premium subscription, the
              RealWithin content already generated for you remains available to
              view on a read-only basis. New Reflections and new
              Premium-generated understanding remain locked until Premium
              access is restored.
            </p>
          </Section>

          <Section title="9. Purchases and Renewals">
            <p>
              Premium purchases made through the Apple App Store or Google Play
              are processed by the applicable marketplace.
            </p>

            <p>
              Where you purchase an auto-renewing subscription, your
              subscription will continue and the marketplace may charge your
              chosen payment method for later subscription periods unless you
              cancel according to the marketplace&apos;s rules.
            </p>

            <p>
              Pricing, renewal timing, billing and cancellation information
              will be shown as part of the purchase process.
            </p>

            <p>
              RealWithin does not directly process your complete payment-card
              details for marketplace purchases.
            </p>
          </Section>

          <Section title="10. Managing or Cancelling Premium">
            <p>
              You can access subscription-management options through RealWithin
              where available or through the marketplace associated with your
              purchase.
            </p>

            <p>
              Deleting the RealWithin application or deleting your RealWithin
              account does not necessarily cancel an active marketplace
              subscription.
            </p>

            <p>
              You should separately cancel an active subscription through
              Apple, Google or the subscription-management options available to
              you.
            </p>
          </Section>

          <Section title="11. Refunds">
            <p>
              Payments made through Apple or Google are generally subject to
              the applicable marketplace&apos;s payment and refund rules.
            </p>

            <p>
              RealWithin cannot guarantee that a refund request will be
              approved.
            </p>

            <p>
              Nothing in these Terms limits any refund or consumer right that
              cannot legally be excluded.
            </p>
          </Section>

          <Section title="12. Account Deletion">
            <p>
              You may delete your RealWithin account using the account-deletion
              functionality provided by RealWithin.
            </p>

            <p>
              You may also visit our{" "}
              <Link
                href="/delete-account"
                className="font-medium text-[#617166] underline underline-offset-4"
              >
                account deletion page
              </Link>{" "}
              or contact <EmailLink /> for assistance.
            </p>

            <p>
              Deleting your account will result in deletion or scheduled
              deletion of information associated with your RealWithin account,
              subject to legitimate legal, security, fraud-prevention or
              regulatory retention requirements.
            </p>

            <p>
              Account deletion is irreversible once completed.
            </p>
          </Section>

          <Section title="13. Notifications">
            <p>
              If you enable notifications, RealWithin may send optional
              notifications relating to your use of the Service.
            </p>

            <p>These may include:</p>

            <List
              items={[
                "daily Reflection reminders;",
                "notifications when a new Pattern is discovered;",
                "notifications when a new Memory is created;",
                "notifications when a new You recognition becomes available; and",
                "other service-related notifications you choose to receive.",
              ]}
            />

            <p>
              Notifications can be managed through RealWithin or your device
              settings.
            </p>

            <p>
              RealWithin aims to avoid displaying sensitive details from your
              reflections or generated insights in notification previews.
            </p>
          </Section>

          <Section title="14. Sharing">
            <p>
              RealWithin may allow you to share certain generated content using
              your device&apos;s sharing functionality.
            </p>

            <p>
              You choose whether to share that content and where it is sent.
            </p>

            <p>
              Once information has been shared outside RealWithin, we cannot
              control how the recipient or third-party service handles it.
            </p>

            <p>
              Consider the personal nature of your RealWithin content before
              sharing it.
            </p>
          </Section>

          <Section title="15. Acceptable Use">
            <p>You agree not to:</p>

            <List
              items={[
                "attempt to interfere with or damage RealWithin;",
                "attempt to gain unauthorised access to accounts, systems or data;",
                "circumvent security or access restrictions;",
                "use automated systems to abuse or overload the Service;",
                "reverse engineer RealWithin where prohibited by applicable law;",
                "use RealWithin to violate applicable law or the rights of another person; or",
                "intentionally misuse the Service.",
              ]}
            />

            <p>
              We may restrict or terminate access where reasonably necessary to
              protect RealWithin, its users or others.
            </p>
          </Section>

          <Section title="16. Intellectual Property">
            <p>
              RealWithin and its associated software, design, branding,
              graphics and other original materials are owned by or licensed to
              RealWithin and are protected by applicable intellectual-property
              laws.
            </p>

            <p>
              These Terms do not transfer ownership of RealWithin&apos;s
              intellectual property to you.
            </p>

            <p>
              Your original reflections remain yours as described in Section 5.
            </p>
          </Section>

          <Section title="17. Availability and Changes">
            <p>RealWithin is an evolving service.</p>

            <p>
              We may add, modify, replace or discontinue features where
              reasonably necessary to develop, maintain, secure or operate the
              Service.
            </p>

            <p>
              We do not guarantee that RealWithin will always be uninterrupted
              or error-free.
            </p>

            <p>
              Where a change materially affects a paid service, we will respect
              applicable consumer rights.
            </p>
          </Section>

          <Section title="18. Termination">
            <p>You may stop using RealWithin at any time.</p>

            <p>
              We may suspend or terminate access where reasonably necessary
              because of serious misuse, security concerns, legal requirements
              or a material violation of these Terms.
            </p>

            <p>
              Termination does not remove rights or obligations that by their
              nature should continue after termination.
            </p>
          </Section>

          <Section title="19. Disclaimer">
            <p>
              To the extent permitted by applicable law, RealWithin is provided
              on an “as available” basis.
            </p>

            <p>
              AI-generated content may contain errors, and RealWithin does not
              guarantee that any reflection, Pattern, Memory, You recognition
              or other generated output accurately describes you or your
              circumstances.
            </p>

            <p>
              Nothing in these Terms excludes warranties or protections that
              cannot legally be excluded.
            </p>
          </Section>

          <Section title="20. Limitation of Liability">
            <p>
              Nothing in these Terms excludes or limits liability where doing
              so would be unlawful.
            </p>

            <p>
              Subject to those rights, RealWithin is not responsible for
              indirect or consequential losses resulting from your use of,
              inability to use or reliance upon AI-generated reflective content
              provided by the Service.
            </p>

            <p>
              Your statutory consumer rights remain unaffected.
            </p>
          </Section>

          <Section title="21. Privacy">
            <p>
              Use of RealWithin is also governed by the{" "}
              <Link
                href="/privacy"
                className="font-medium text-[#617166] underline underline-offset-4"
              >
                RealWithin Privacy Policy
              </Link>
              , which explains how personal information is collected,
              processed, stored and deleted.
            </p>
          </Section>

          <Section title="22. Changes to These Terms">
            <p>
              We may update these Terms as RealWithin develops or legal
              requirements change.
            </p>

            <p>
              The current version will display its most recent update date.
            </p>

            <p>
              Where required by law, we will provide appropriate notice of
              material changes.
            </p>

            <p>
              Continuing to use RealWithin following a change will constitute
              acceptance only where permitted by applicable law.
            </p>
          </Section>

          <Section title="23. Applicable Rights">
            <p>
              These Terms do not remove consumer, privacy or other rights that
              cannot be excluded under mandatory laws that apply to you.
            </p>
          </Section>

          <Section title="24. Contact">
            <p>
              Questions about these Terms or RealWithin can be sent to:
            </p>

            <p className="font-medium text-[#414641]">
              RealWithin
              <br />
              V. Bance, trading as RealWithin
              <br />
              <EmailLink />
            </p>
          </Section>
        </div>
      </main>

      <Footer />
    </div>
  );
}

function Header() {
  return (
    <header className="border-b border-[#e3ddd2]">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10">
        <Link href="/" className="flex items-center gap-3">
          <span className="relative h-9 w-9 overflow-hidden rounded-full border-2 border-[#303430]">
            <span className="absolute inset-y-0 right-0 w-1/2 bg-[#303430]" />
          </span>

          <span className="font-serif text-2xl text-[#292d29]">
            RealWithin
          </span>
        </Link>

        <nav className="flex items-center gap-5 text-sm text-[#666c66]">
          <Link
            href="/#journey"
            className="hidden transition hover:text-[#303430] sm:inline"
          >
            How it works
          </Link>

          <Link
            href="/try"
            className="rounded-full bg-[#68786b] px-5 py-2.5 font-semibold text-white transition hover:bg-[#5d6c60]"
          >
            Try RealWithin
          </Link>
        </nav>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer className="border-t border-[#ded8cc]">
      <div className="mx-auto flex max-w-7xl flex-col gap-5 px-6 py-8 text-sm text-[#777c76] sm:flex-row sm:items-center sm:justify-between lg:px-10">
        <p>© 2026 RealWithin</p>

        <div className="flex flex-wrap gap-5">
          <Link href="/privacy" className="hover:text-[#343934]">
            Privacy
          </Link>

          <Link href="/terms" className="hover:text-[#343934]">
            Terms
          </Link>

          <Link href="/support" className="hover:text-[#343934]">
            Support
          </Link>

          <Link href="/delete-account" className="hover:text-[#343934]">
            Delete account
          </Link>
        </div>
      </div>
    </footer>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="border-t border-[#e4ded3] pt-8">
      <h2 className="text-xl font-semibold tracking-tight text-[#3f443f] sm:text-2xl">
        {title}
      </h2>

      <div className="mt-4 space-y-4">
        {children}
      </div>
    </section>
  );
}

function List({ items }: { items: string[] }) {
  return (
    <ul className="list-disc space-y-2 pl-6">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

function EmailLink() {
  return (
    <a
      href="mailto:support@realwithin.com"
      className="font-medium text-[#617166] underline underline-offset-4"
    >
      support@realwithin.com
    </a>
  );
}